ALTER TABLE ITReturnDetails
ADD RITotalIncome DECIMAL(18,2) NULL
GO

ALTER TABLE ITReturnDetails
ADD RISurcharge DECIMAL(18,2) NULL
GO

ALTER TABLE ITReturnDetails
ADD RIEducationCess DECIMAL(18,2) NULL
GO

ALTER TABLE ITReturnDetails
ADD MATTotalIncome DECIMAL(18,2) NULL
GO

ALTER TABLE ITReturnDetails
ADD MATSurcharge DECIMAL(18,2) NULL
GO

ALTER TABLE ITReturnDetails
ADD MATEducationCess DECIMAL(18,2) NULL
GO
