USE [LitigationApp]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_IT_RETURN_DOCUMENT_LIST]    Script Date: 9/4/2018 10:26:30 PM ******/
DROP PROCEDURE [dbo].[SP_GET_IT_RETURN_DOCUMENT_LIST]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_IT_RETURN_DOCUMENT_LIST]    Script Date: 9/4/2018 10:26:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_GET_IT_RETURN_DOCUMENT_LIST]
(	
	@COMPANY_ID BIGINT = NULL,
	@FYAY_ID BIGINT = NULL,
	@IT_RETURN_DETAILS_ID BIGINT = NULL,
	@IT_HEAD_ID BIGINT = NULL,
	@IT_RETURN_DOCUMENT_ID BIGINT = NULL
)
AS

BEGIN

--EXEC [SP_GET_IT_RETURN_DOCUMENT_LIST] 1, 1

SELECT ITRD.Id
	, ITRD.ITReturnDetailsId
	, ITRD.ITHeadId
	, ITH.ExcelSrNo
	, ITH.[Description] ITHeadDescription
	, ITH.PropertyName
	, COMP.Id AS CompanyId
	, COMP.CompanyName
	, FYAY.Id AS FYAYId
	, FYAY.FinancialYear
	, FYAY.AssessmentYear
	, ITRD.[FileName]
	, ITRD.FilePath
	, ITRD.Active
	, ITRD.AddedBy
	, ITRD.AddedDate
	, ITRD.ModifiedBy
	, ITRD.ModifiedDate	
	FROM [ITReturnDocuments] ITRD
	INNER JOIN ITReturnDetails ITR on ITR.Id = ITRD.ITReturnDetailsId
	INNER JOIN ITHeadMaster ITH ON ITH.Id = ITRD.ITHeadId
	INNER JOIN CompanyMaster COMP ON COMP.Id = ITR.CompanyId
	INNER JOIN FYAYMaster FYAY ON FYAY.Id = ITR.FYAYId
	WHERE ITRD.Active = 1
	AND (@COMPANY_ID IS NULL OR COMP.Id = @COMPANY_ID)
	AND (@FYAY_ID IS NULL OR FYAY.Id = @FYAY_ID)
	AND (@IT_RETURN_DETAILS_ID IS NULL OR ITR.Id = @IT_RETURN_DETAILS_ID)
	AND (@IT_HEAD_ID IS NULL OR ITH.Id = @IT_HEAD_ID)
	AND (@IT_RETURN_DOCUMENT_ID IS NULL OR ITRD.Id = @IT_RETURN_DOCUMENT_ID)
	ORDER BY ITRD.AddedDate DESC
END



GO


